// export const ADDSUJET="ADDSUJET";
// export const INSCRIRE="INSCRIRE";
// export const EDITSUJET="EDITSUJET";
// export const DELETESUJET="DELETESUJET"
// export const GETSUJET="GETSUJET"
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOADING = "LOADING";
export const FAIL = "FAIL";
export const GET_CURRENT = "GET_CURRENT";
export const LOGOUT = "LOGOUT";